/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebasimagenes;

import java.util.Random;

/**
 *
 * @author a16pablovc
 */
public class NewJFrame extends javax.swing.JFrame {
  int a,b;   int mapa=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        Random r=new Random();
        a=1;
      b=0;
   
//        a=r.nextInt(3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        la = new javax.swing.JLabel();
        maps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoMouseMoved(evt);
            }
        });
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoMouseClicked(evt);
            }
        });

        la.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebasimagenes/esde.png"))); // NOI18N
        la.setText("jLabel1");
        la.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laMouseClicked(evt);
            }
        });

        maps.setPreferredSize(new java.awt.Dimension(30, 30));
        maps.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mapsMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(maps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(819, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1932, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laMouseClicked
           
         fondo.removeAll();
         fondo.add(la);
         fondo.add(maps);
 
         
          Random r=new Random();
          if(a==1){a=0;}else{a=1;}
//if(a==1&&b==0){b=1;a=1;}
//if(a==1&&b==1){b=0;a=0;}
          System.out.println("a="+a);
           
          Imagen_1 Imagen_1 = new Imagen_1(2);
                maps.add(Imagen_1);
            //    maps.setSize(30,30);;
            maps.repaint();
          
                 Imagen_1 = new Imagen_1(a);
                fondo.add(Imagen_1);
            fondo.repaint();
//            else{   
//                Imagen_1 Imagen = new Imagen_1(a);
//                    fondo.add(Imagen);
//                    fondo.repaint();}
    

    }//GEN-LAST:event_laMouseClicked

    private void fondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseClicked
 System.out.println(evt.getX()+" x   y "+evt.getY());
 int x=evt.getX();
int y=evt.getY();
 if(x>720){
 if(y>400){System.out.println("ourense");}else{
     System.out.println("lugo");
 }
 
 
 }
 
 
 else{
  if(y>400){System.out.println("pontevedra ");}else{
      System.out.println("coruña");
 }
 
 
 }
    }//GEN-LAST:event_fondoMouseClicked

    private void mapsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapsMouseMoved
 

        Imagen_1 Imagen_1 = new Imagen_1(3);
        System.out.println("mev");     
        if(mapa==0){maps.removeAll();mapa=1;}
                maps.add(Imagen_1);
             
            maps.repaint();
    }//GEN-LAST:event_mapsMouseMoved

    private void fondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseMoved
        System.out.println(evt.getX()+"   x   y  "+evt.getY());
        if(mapa==1){maps.removeAll();mapa=0;
         Imagen_1 Imagen_1 = new Imagen_1(2);
                maps.add(Imagen_1);
            //    maps.setSize(30,30);;
            maps.repaint();
        
        
        }
        
    }//GEN-LAST:event_fondoMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel la;
    private javax.swing.JLabel maps;
    // End of variables declaration//GEN-END:variables
}
